27 my account
LeWricka/climbing-plan-madonna pull request #10
Opened 2021-05-27 07:08 UTC by 01Joel-Hazas

**Issue**
- https://trello.com/c/jJsJARG4/27-my-account

**Solution**
- He implementado la pantalla del usuario con la ayuda de la plantilla de generic profile.

**How to try it**
1. Go to http://localhost:8088/myAccount

**Concerns**

2021-05-27 07:48 UTC, LeWricka requested changes

2021-05-27 07:48 UTC, LeWricka commented on src/app/Actions/Fortify/UpdateUserProfileInformation.php
> +        if ($input['email'] !== "$user->email" &&
No entiendo esta parte, ese user que se utiliza ahí no puede nuestro user...lo comentamos?

2021-05-27 07:48 UTC, LeWricka commented on src/core/Users/Infrastructure/Database/EloquentUserDataSource.php
>  namespace Core\Users\Infrastructure\Database;
Esta clase no la necestiamos, no tenemos nada relacionado con eloquent

2021-05-27 07:48 UTC, LeWricka commented on src/routes/web.php
> +//Route::middleware(['auth' ])->group(function () {
elmina esto si no lo usamos

2021-05-27 07:48 UTC, LeWricka commented on src/tests/Integration/DataSources/EloquentUserDataSourceTest.php
Estea clase puedes borrarla también

2021-05-27 07:48 UTC, LeWricka commented on src/tests/Unit/Services/EarlyAdopter/IsEarlyAdopterServiceTest.php
>  namespace Tests\Unit\Services\EarlyAdopter;
Y esta también

2021-05-27 07:48 UTC, LeWricka commented on src/database/factories/UserFactory.php
>  namespace Database\Factories;
Este factory no lo necesitamos

2021-05-31 08:35 UTC, EkaitzTorregrosa commented on src/resources/views/auth/forgot-password.blade.php
> +<head>
No podemos extender de la plantilla base?

2021-06-01 09:28 UTC, closed without merging