17 daily schedule
LeWricka/climbing-plan-madonna pull request #3
Opened 2021-05-19 08:46 UTC by EkaitzTorregrosa

**Issue**
- https://trello.com/c/xWpEVn02/17-daily-schedule

**Solution**
- Implementado el dateClick para pasar la fecha clickada al DailyScheduleController mediante la url. 

**How to try it**
1. Go to: http://localhost:8088/dailySchedule/2021-05-14 o http://localhost:8088/main y haz click sobre un día.

**Concerns**

2021-05-21 07:09 UTC, LeWricka requested changes

2021-05-21 07:09 UTC, LeWricka commented on src/app/Http/Controllers/DailyScheduleController.php
> +
elimina este espacio

2021-05-21 07:09 UTC, LeWricka commented on src/app/Http/Controllers/CalendarController.php
> +        $routine1 = new Routine("First Routine", new DateTime('2021-05-14'), new DateTime('2021-05-16'), "#e04f1a");
Aquí tendremos que pensar en cómo asignar los colores ya que es algo de vista y no nos va a venir del backend

2021-05-21 07:09 UTC, LeWricka commented on src/app/Http/Controllers/DailyScheduleController.php
> +    {
Cuando tengamos el backend, le meteremos mano a esto

2021-05-21 07:09 UTC, LeWricka commented on src/resources/views/pages/dailySchedule.blade.php
> +<head>
De la misma forma que hemos extraído el navbar, vamos a extraer el head con todos lo metas

2021-05-21 07:09 UTC, LeWricka commented on src/app/Models/Routine.php
> +        return ["title" => $this->getName(), "start" => $this->getStart()->format('Y-m-d'), "end" => $this->getEnd()->format('Y-m-d'), "color" => $this->getColor()];
Por qué tienes que pasarlo a un array de key value? cuidado que esto no es un json.

2021-05-21 07:47 UTC, EkaitzTorregrosa commented on src/resources/views/pages/dailySchedule.blade.php
> +<head>
¿Esto lo hago mejor en la rama 19_navbar?

2021-05-21 12:37 UTC, EkaitzTorregrosa commented on src/app/Models/Routine.php
> +        return ["title" => $this->getName(), "start" => $this->getStart()->format('Y-m-d'), "end" => $this->getEnd()->format('Y-m-d'), "color" => $this->getColor()];
Porque así paso un array de rutinas(ClaveValor) al js del calendario con los datos que este necesita para mostrar los eventos.
Decidí dejarlo así porque no sabía como acceder a los datos de un array de Rutinas desde el js del calendario.

2021-05-22 08:04 UTC, LeWricka approved these changes
ok to merge

2021-05-22 08:04 UTC, LeWricka commented on src/app/Http/Controllers/CalendarController.php
> +            $routine1->routineToKeyValue(),
Tengo alguna idea para mejorar esto. Cuando cojamos los datos de bbdd le meteremos mano

2021-05-22 08:04 UTC, LeWricka commented on src/resources/views/pages/dailySchedule.blade.php
> +<head>
ok

2021-05-22 08:54 UTC, merged