[19] - Navbar implemetado en un componente
LeWricka/climbing-plan-madonna pull request #5
Opened 2021-05-20 11:25 UTC by EkaitzTorregrosa

**Issue**
- https://trello.com/c/kZHiD4Rr/19-navbar

**Solution**
- Extraer el navbar a un componente para implementarlo en las diferentes pantallas. 

**How to try it**
1. Go to: http://localhost:8088/main

**Concerns**
- El apartado de "Charts" no redirige a nada.

2021-05-21 07:16 UTC, 01Joel-Hazas commented on src/app/View/Components/Navbar.php
> +        //
¿Es necesario este constructor vacío?

2021-05-21 07:16 UTC, 01Joel-Hazas commented on src/resources/views/components/navbar.blade.php
> +        <a class="font-w600 text-dual" href="index.html">
¿No crees que deberíamos redireccionar a la ruta principal ?

2021-05-21 07:37 UTC, LeWricka requested changes

2021-05-21 07:37 UTC, LeWricka commented on src/app/View/Components/Navbar.php
> +    {
No queremos constructores vacíos, no aportan valor. Por defecto, no tener es lo mismos que tener uno vacío

2021-05-21 07:37 UTC, LeWricka commented on src/resources/views/components/navbar.blade.php
> +            <div class="dropdown d-inline-block ml-2">
Ya que estamos, limpia esto para dejar solo lo que necesitamos

2021-05-22 07:55 UTC, LeWricka approved these changes
quedan muchas cosas por limpiar pero ya lo haremos en la https://trello.com/c/NPYKVokh/25-improve-blade-pages

Ok to merge

2021-05-22 08:54 UTC, merged